version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'isladot'
    reviewers:
      - 'isladot'
    commit-message:
      prefix: 'npm'
      prefix-development: 'npm-dev'
    target-branch: 'dev'
    ignore:
      - dependency-name: 'node-fetch'
