version: 2
updates:
  - package-ecosystem: 'npm'
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - 'isladot'
    reviewers:
      - 'isladot'
    commit-message:
      prefix: 'npm'
      prefix-development: 'npm-dev'
    target-branch: 'dev'
